<a href="https://colab.research.google.com/github/amannayanmujawar/Deep-Learning/blob/main/Tensors_and_Neural_network_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Tensors**

In [1]:
#what is a tensor?
#tensors are specialized data structures that very similar to array's and matrics
# we use the tensors to encode the inputs and outputs of model
# these are similar to numpy arrays
# tensors can run on GPU or other hardware accelrators.
# so tensor is a container for numerical data.
# ex:- 1 number --> scaler
#      1D collection --> [1,2,3,4,5,6] --> vectors
#      matrix --> 2D
#      tensors --> 3D,4D,5D...
# age = [25,30,35,40] --> vector
# Age     salary
# 25       30000
# 30       45000
# 35       60000
# 2D --> matrix
# for ex:- take image --> Height * width * channel
#                          224   *  224  *  3
# for a batch images --> batch * Height * width * channel  --> 4--dimensional tensor

In [2]:
# There are 2 frame works to work with tensors
# 1. pytorch
# 2. tensorflow

pytorch installation / import Pytorch

In [3]:
import torch
import numpy as np

In [4]:
# print the version of pytorch
print(torch.__version__)

# we use pytorch to  --> follows
# create tensors
# perform mathematical operations
# calculate gradient
# build neural networks
# train deep learning

2.11.0+cu128

#Create tensors

In [5]:
# scalar
x = torch.tensor(10)
print(x)
print(type(x))
print(x.ndim)

tensor(10)
<class 'torch.Tensor'>
0

In [6]:
# vector
L = [10,20,30,40,50]
# convert to tensors
a = torch.tensor(L)
print(a)
print(a.ndim)
print(a.shape)

tensor([10, 20, 30, 40, 50])
1
torch.Size([5])

In [7]:
# create  tensor by using the matrics
b = torch.tensor([[10,20,30],[40,50,60]])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)
print(b.numel())

tensor([[10, 20, 30],
        [40, 50, 60]])
2
torch.Size([2, 3])
torch.int64
6

In [8]:
# Note :- for neural networks we work with floating point values
b = b.float()
print(b)

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [9]:
# weights + multiply + gradient + optimization so floating point temsors are commonly used for this point

**Tensor creation function**

In [10]:
c = torch.zeros(3,4)
print(c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
# create tensors of ones with 2 rows and 3 columns
d = torch.ones(2,3)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# create random tensors
e = torch.rand(3,3)
print(e)

tensor([[0.2879, 0.9723, 0.0069],
        [0.4976, 0.0279, 0.0268],
        [0.8830, 0.7473, 0.6173]])

In [13]:
# create random numbers with normal distribution data
n = torch.randn(3,3)
print(n)

tensor([[ 0.0157, -0.4308, -1.5954],
        [-0.4505, -0.8715,  0.8197],
        [-0.3903,  1.1529,  0.4117]])

In [14]:
# generate a range of tensors
r = torch.arange(0,10)
print(r)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Matrix multiplication**

In [15]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
c = torch.matmul(a,b)
print(c)

tensor([[19, 22],
        [43, 50]])

reshape of an tensors

In [16]:
c = np.arange(12)
print(c)
# reshape it in to 3 rows and 4 columns
print(c.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [17]:
# create a tensor from numpy arrays
a = np.array([[12,20],[30,40]])
print(a)

[[12 20]
 [30 40]]

In [18]:
tensor = torch.from_numpy(a)
print(tensor)

tensor([[12, 20],
        [30, 40]])

In [19]:
a = tensor.numpy()
print(a)

[[12 20]
 [30 40]]

In [20]:
# check the GPU's
print(torch.cuda.is_available())
# we need to enable the GPU's

True

In [21]:
# move a tensor to GPU
x = torch.tensor([1,2,3]).float()
device = torch.device("cuda" if torch.cuda.is_available() else "CPU")
x = x.to(device)
print(x.device)

cuda:0

In [22]:
# LLM --> millions/ billions of parameters --> matrix multiplication --> GPU --> tensor calculation

In [23]:
# pytorch automatically calculates the derivative
# gradient --> find the list loss
x = torch.tensor(3.0, requires_grad=True)
y = x**2
print(y)

tensor(9., grad_fn=<PowBackward0>)

In [24]:
y.backward()
print(x.grad)

# The above execution is the foundation for backward propagation

tensor(6.)

**Neural Networks**  contains --> input layer --> hidden layers --. output layer

In [25]:
# Age , Incoome , experience --> purchase probability
# understand the neurons
# a neuron can be perform like below
# z = x1w1 + x2w2 + x3w3 + b
# then a activation function is applied to above formula
# output = activation(z)
# ReLU , Sigmoid , softmax

**predict whether a customer will leave a company or not**

The above test case relates to rpoduct base company so a data scientist needs to predict  who is going leave the products

In [26]:
# features --> Age, Tenure Monthly charges, support calls
# churn ---> target(y)
# 1--> customer left
# 0--> customer stayed

**import the required libraries**

In [27]:
import numpy as np  # --> nuperical operation
import pandas as pd  #--> data handling
import matplotlib.pyplot as plt   #--> Data visualization

In [28]:
import torch
import torch.nn as nn
import torch.optim as optim  # used for optimization and weight updates

In [29]:
# check the weather GPU is available or  not
device = torch.device("cuda" if torch.cuda.is_available() else "CPU")
print("Device",device)

Device cuda

In [30]:
url = "https://raw.githubusercontent.com/Nas-virat/Telco-Customer-Churn/master/Telco-Customer-Churn.csv"

df = pd.read_csv(url)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [31]:
# what is each row represents in above data?
# ech customer details
#Q) what are we trying to predict?
# churn
#Q) which columns shouldnot be used as a predictive features?
#customerID --> does not dexcribe their churn behaviour

In [32]:
# check the shape of the data
df.shape

(7043, 21)

In [33]:
# get the overall information of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [34]:
# get the summary of the data
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [35]:
# check the null values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [36]:
# check the disrtibution of churns
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [37]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [38]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors='coerce')

In [39]:
df['TotalCharges'].isnull().sum()

np.int64(11)

In [40]:
# these are very less values and compare this values with others rows
df[df['TotalCharges'].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [41]:
df = df.dropna()

In [42]:
df.shape

(7032, 21)

In [43]:
df['Churn']
# convert yes in to 1 and no in to 0
df['Churn'] = df['Churn'].map({"No":0,"Yes":1})

In [44]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [45]:
df.columns
cl = ['gender','Partner', 'Dependents','PhoneService','OnlineSecurity', ]

In [46]:
# remove the customer ID
df = df.drop('customerID',axis=1)

In [47]:
# define features and target varibale
x = df.drop("Churn",axis=1)
y = df['Churn']

**categorical variables**

In [48]:
# gender , partner,depedents,Internetservisec,contract, paymentmethod
# encode the data because NN and ML cannot categorical data
# there is no order in my data we do one hot encoding
# in pandas to do one hot encoidng we use the method --> pd.get_dummies
x = pd.get_dummies(x,drop_first=True)

In [49]:
x.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False

**Train/Test split**

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

**scale the data**

In [51]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

**To apply the neural networks convert the data into tensors**

In [52]:
import torch
x_train_tensor = torch.tensor(x_train,dtype=torch.float32)
x_test_tensor = torch.tensor(x_test,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values,dtype=torch.float32).reshape(-1,1) # convert the y 1D to 2D format
y_test_tensor = torch.tensor(y_test.values,dtype=torch.float32).reshape(-1,1)

In [53]:
print(x_train_tensor.shape)

torch.Size([5625, 30])

In [54]:
input_features = x_train_tensor.shape[1]
print(input_features)

30

**Build the neural networks**

In [55]:
import torch.nn as nn
class ChurnModel(nn.Module):
  def __init__(self,input_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(input_features,32),
        nn.ReLU(),
        nn.Linear(32,16),
        nn.ReLU(),
        nn.Linear(16,1),
        nn.Sigmoid()
      )
  def forward(self,x):
    return self.network(x)

**create the model**

In [56]:
model = ChurnModel(input_features)
print(model)

ChurnModel(
  (network): Sequential(
    (0): Linear(in_features=30, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=16, bias=True)
    (3): ReLU()
    (4): Linear(in_features=16, out_features=1, bias=True)
    (5): Sigmoid()
  )
)

**claculate the loss**

In [57]:
criterion = nn.BCELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr = 0.01

)

In [58]:
epochs = 100
loss_history = []
for epoch in range(epochs):
  # forward pass
  predictions = model(x_train_tensor)
  #calculate loss
  loss = criterion(predictions,y_train_tensor)
  #gradient --> calculate list loss
  optimizer.zero_grad()
  # Backpropagation
  loss.backward()
  #update weights
  optimizer.step()

  loss_history.append(loss.item())

  if (epoch + 1) % 10 == 0:
    print(
        f"epoch [{epoch+1}/{epochs}]"
        f"loss: {loss.item():.4f}"
    )

epoch [10/100]loss: 0.4604
epoch [20/100]loss: 0.4292
epoch [30/100]loss: 0.4161
epoch [40/100]loss: 0.4069
epoch [50/100]loss: 0.4012
epoch [60/100]loss: 0.3959
epoch [70/100]loss: 0.3903
epoch [80/100]loss: 0.3847
epoch [90/100]loss: 0.3797
epoch [100/100]loss: 0.3745